### ISSUE TITLE
Chat will not send messages when embedded on chromium (ubuntu 14)

### ISSUE THREAD

**Issue by evanmccarter** [InfraRaven/spooks-chatjs#3]
The chat chat will not send messages when embedded on chromium on ubuntu 14

If http://this.spooks.me is embedded in an iframe, the page will load but pressing "enter" creates a newline, the equivalent of pressing shift+enter
Additionally, if a custom subdomain is embedded (http://example.spooks.me) the iframe doesn't load at all

**Comment by RandomsDude** [comment]
Fixed.

**Comment by RandomsDude** [comment]
Not Fixed

**Comment by RandomsDude** [comment]
Fixed. Closed.
