### ISSUE TITLE
jester kicked me and now "this channel is private"

### ISSUE THREAD

**Issue by evanmccarter** [InfraRaven/spooks-chatjs#301]
jester kicked me and now when i connect all i get is 
"Channel is private."
"Disconnected"

please add numbers back to the end of new user's names and tell jester to grow up

**Comment by evanmccarter** [comment]
also unban me or whatever

**Comment by bitchnigga** [comment]
This is a new function supers have to make a channel /private. This kicks all unregistered names and locks them out.

**Comment by evanmccarter** [comment]
Well then there needs to be an opportunity to login as a registered nick before being completely disconnected, because if I wasn't logged in at the time how would I have gotten access back? It's putting a brick wall up to everyone not currently logged in to the channel, which is fine if that's what you want, but it's bullshit for everyone else, including regulars who just happened to be gone at the time. 
There needs to be a way to log in before being completely disconnected. A mute function would probably fulfill that purpose (we already have /block), and muting all new users automatically while still allowing them to log in (not just disconnecting immediately) would probably work. 

To go further and make this more easily maintained, there could be a global /block list so that new users don't have to be automatically or individually added to every user's block list, just added to the single global block list. Modifying individual user's block lists could quickly get complex, and having a global list would keep random connections out of individual lists, making them much more usable. 
Moreover, during times of heavy spam, there could be a cooldown time between users joining and being able to talk, and this cooldown time could be automatically set based on how many recent connections the site has gotten, which would effectively be automatic spam prevention, meaning admins don't have to be present to cut down on spam. 

high spam + connections = automatic global /block plus a long time before new users being able to talk
low spam + connections = no automatic block and a short time before being removed from the list
admin involvement needed to make this work = 0

Also, I was still sent the /note and probably the /topic before being disconnected, so there is opportunity for people to spam HTML refreshes to slow down the site.

**Comment by jerrystarfield** [comment]
I think this issue is resolved.

**Comment by get52** [comment]
>was never fixed
>back in spooks days
>this is fucking us over right now on forgetme

You predicted the future evan.

**Comment by evanmccarter** [comment]
Predicting the future is the whole purpose of having a brain
But I didn't need to predict the future, only perceive a (then) present
problem

>it's a feature not a bug

Someone should reopen this bug because it's not satisfactorily solved, and
never was

If private is to "kick unregistered users", it should at least give people
5 seconds to login, because if it doesn't it kicks registered users as
well. The topic is even broadcasted on a private channel, meaning there is
a client/server connection at some point, but everyone is insta-kicked.
Plus, broadcasting the topic and note isn't very private.

Really, private should give everyone a kind of mute in reverse: being
unable to hear instead of speak. Set everyone of a lower level than the
initiator to "reverse mute" on the command, and things are as they should
be.

But devs aren't going to like that solution because it takes some work in
the user roles area
So continue calling the "kick everyone automatically command" a feature

**Comment by get52** [comment]
True, I think it's a bug as well.

**Comment by LandonPowell** [comment]
This is hilarious. 
Private is such a pile of shit. I'd move for whoever code-monkey'd it be beheaded.

**Comment by get52** [comment]
kek yes

**Comment by jerrystarfield** [comment]
Hey guys, I marked this as resolved and there was probably a good reason! Or maybe I was just drunk idk

**Comment by get52** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/8e28203a2d",
            "name": "Claim It Now"
          },
          "description": "Claim It Now"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Getindor sent you a voucherfor a free service on Fiverr.
    

    
        Fiverr is the world's largest marketplace for services,where you can get everything you need starting at $5.
    

    
        Your voucher is waiting for you. Get started now!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Claim Your Free Service
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2015, FIVERR®, GIG®, GIGS®, I WILL__for$5, The Things People Do For $5, DamnQuickPay, Fiverr graphics, logos, scripts, terms of use, instructions, designs and others service names are the trademarks and copyright of Fiverr International Limited.Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
